import { ItemView, Notice, WorkspaceLeaf } from "obsidian";
import type VaultOrganizerPlugin from "./main";
import type { NoteRecord, ProjectFolder } from "./types";

export const VIEW_TYPE = "vault-organizer-dashboard";

export class VaultOrganizerDashboard extends ItemView {
  private settingsOpen = false;
  private query = "";
  constructor(leaf: WorkspaceLeaf, private plugin: VaultOrganizerPlugin) { super(leaf); }
  getViewType(): string { return VIEW_TYPE; }
  getDisplayText(): string { return "Vault Organizer"; }
  getIcon(): string { return "layout-dashboard"; }
  async onOpen(): Promise<void> { await this.render(); }
  async render(): Promise<void> {
    const root = this.containerEl.children[1] as HTMLElement; root.empty(); root.addClass("vault-organizer-dashboard");
    const data = this.plugin.repository.dashboard(); const projects = this.plugin.repository.getProjectFolders();
    const hero = root.createDiv({ cls: "vault-organizer-hero" }); hero.createEl("div", { text: "VAULT WORKSPACE", cls: "vault-organizer-eyebrow" }); hero.createEl("h1", { text: "Vault Organizer" }); hero.createEl("p", { text: "A calmer home for quick notes and project workspaces." });
    const actions = hero.createDiv({ cls: "vault-organizer-actions vault-organizer-primary-actions" }); this.action(actions, "Quick note", () => this.plugin.openCapture("quick-note"), true); this.action(actions, "New project", () => this.plugin.openCapture("project"), true); const settings = this.action(actions, this.settingsOpen ? "Close settings" : "Settings", () => { this.settingsOpen = !this.settingsOpen; void this.render(); }); settings.setAttr("aria-expanded", String(this.settingsOpen)); if (this.settingsOpen) this.renderSettings(hero);
    const notice = !data.quickNotes.totalFiles && !projects.length ? root.createDiv({ cls: "vault-organizer-welcome" }) : null; if (notice) { notice.createEl("strong", { text: "Start with a workspace" }); notice.createEl("p", { text: "Confirm your roots in Settings, then create a quick note or project." }); }
    const metrics = root.createDiv({ cls: "vault-organizer-metrics" }); this.metric(metrics, "Quick notes", data.quickNotes.totalFiles, data.quickNotes.ownedFiles, () => void this.plugin.openQuickFiles()); this.metric(metrics, "Projects", projects.length, data.projects.ownedFiles, () => void this.plugin.openProjects());
    const search = root.createEl("input", { cls: "vault-organizer-search", attr: { type: "search", placeholder: "Search your organized notes…", "aria-label": "Search Vault Organizer" } }); search.value = this.query; const results = root.createDiv({ cls: "vault-organizer-search-results" }); search.oninput = () => { this.query = search.value; this.renderSearch(results); }; if (this.query) this.renderSearch(results);
    const grid = root.createDiv({ cls: "vault-organizer-grid" }); this.panel(grid, "Recent quick notes", data.quickNotes.recentFiles, "quick-note"); this.projectPanel(grid, "Project workspaces", projects); this.recentPanel(grid, "Recent projects", data.projects.recentFiles, "project");
  }
  private renderSettings(parent: HTMLElement): void { const panel = parent.createDiv({ cls: "vault-organizer-settings-panel" }); panel.createEl("div", { text: "SETTINGS", cls: "vault-organizer-eyebrow" }); panel.createEl("p", { text: "Storage, naming, and maintenance tools live here so the workspace stays focused." }); const actions = panel.createDiv({ cls: "vault-organizer-actions" }); this.action(actions, "Open plugin settings", () => this.plugin.openSettings(), true); this.action(actions, "Review migration & repair", () => this.plugin.reviewMaintenance()); this.action(actions, "Repair configured trees", () => void this.plugin.repairTrees()); }
  private panel(parent: HTMLElement, title: string, files: NoteRecord[], kind: "quick-note" | "project"): void { const panel = parent.createDiv({ cls: "vault-organizer-panel" }); panel.createEl("div", { text: title.toUpperCase(), cls: "vault-organizer-panel-kicker" }); panel.createEl("h2", { text: title }); if (!files.length) panel.createEl("p", { text: "Nothing here yet.", cls: "vault-organizer-muted" }); for (const record of files.slice(0, 8)) this.fileRow(panel, record, kind); }
  private recentPanel(parent: HTMLElement, title: string, files: NoteRecord[], kind: "quick-note" | "project"): void { this.panel(parent, title, files, kind); }
  private projectPanel(parent: HTMLElement, title: string, projects: ProjectFolder[]): void { const panel = parent.createDiv({ cls: "vault-organizer-panel vault-organizer-project-panel" }); panel.createEl("div", { text: "PROJECTS", cls: "vault-organizer-panel-kicker" }); panel.createEl("h2", { text: title }); if (!projects.length) panel.createEl("p", { text: "Create a project to give it a dedicated workspace.", cls: "vault-organizer-muted" }); for (const project of projects.slice(0, 8)) { const row = panel.createDiv({ cls: "vault-organizer-project-row" }); const info = row.createDiv(); info.createEl("strong", { text: project.name }); info.createEl("span", { text: `${project.files} file${project.files === 1 ? "" : "s"}` }); const open = row.createEl("button", { text: "Open" }); open.onclick = () => void this.plugin.openProject(project); } }
  private fileRow(parent: HTMLElement, record: NoteRecord, kind: "quick-note" | "project"): void { const row = parent.createDiv({ cls: "vault-organizer-file-row" }); const button = row.createEl("button", { text: record.title, cls: "vault-organizer-file-link" }); button.onclick = () => void this.plugin.openRecord(record, kind); row.createEl("span", { text: new Date(record.modified).toLocaleDateString(), cls: "vault-organizer-muted" }); }
  private renderSearch(parent: HTMLElement): void { parent.empty(); const query = this.query.trim().toLocaleLowerCase(); if (!query) return; const matches = this.plugin.repository.getRecords().filter(record => `${record.title} ${record.path} ${record.tags.join(" ")}`.toLocaleLowerCase().includes(query)); parent.createEl("h2", { text: `Search results (${matches.length})` }); if (!matches.length) parent.createEl("p", { text: "No matching notes.", cls: "vault-organizer-muted" }); for (const record of matches.slice(0, 20)) this.fileRow(parent, record, record.ownership?.kind ?? record.legacyType ?? "quick-note"); }
  private action(parent: HTMLElement, label: string, fn: () => void, primary = false): HTMLButtonElement { const button = parent.createEl("button", { text: label, cls: primary ? "mod-cta" : "" }); button.onclick = fn; return button; }
  private metric(parent: HTMLElement, label: string, value: string | number, detail: string | number, fn?: () => void): void { const card = parent.createDiv({ cls: `vault-organizer-metric-card${fn ? " is-actionable" : ""}` }); if (fn) { card.tabIndex = 0; card.setAttr("role", "button"); card.onclick = fn; card.onkeydown = event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); fn(); } }; } card.createEl("strong", { text: String(value) }); card.createEl("span", { text: label }); card.createEl("small", { text: typeof detail === "number" ? `${detail} managed` : String(detail) }); }
}
